# Generated by Django 5.0.2 on 2024-02-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='City',
        ),
    ]
