# Generated by Django 5.0.2 on 2024-02-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_topic_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
