# Generated by Django 5.0.2 on 2024-02-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_city_topic_alter_room_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='city',
        ),
    ]
